name: Build

on:
    workflow_dispatch:
        inputs:
          sdk_link:
            description: "Link to SDK (zip file): "
            required: true

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Download SDK
              run: |
                    $sdk_link = ${{ github.event.inputs.sdk_link }}
                    Invoke-WebRequest -Uri $sdk_link -OutFile sdk.zip
                    Expand-Archive -Path sdk.zip -DestinationPath CppSDK

            - name: Set up MSVC environment
              uses: microsoft/setup-msbuild@v1.0.0

            - uses: lukka/get-cmake@latest

            - name: Configure CMake
              run: cmake -B build -S .

            - name: Build project
              run: cmake --build build --config Release

            - name: Archive artifacts
              uses: actions/upload-artifact@v2
